### ISSUE TITLE
Percentage display cant be used with oclockvita.

### ISSUE THREAD

**Issue by TheRadziu** [joel16/VITABattery#1]
Both plugins are using same shortcuts(select+up/down) to enable and disable menu(for oclock)/display percentage(vitabattery). Closing oclock's menu also removes vitabattery's percentage from the screen. 
Only thing that works is remaining time display since it uses different binding to enable it.

**Comment by joel16** [comment]
Fixed https://github.com/joel16/VITABattery/commit/05c230b93e4204d2abeabeb2946ea75af6152a95

Please use the latest release (v1.4 as of now).

Start Up -> Current battery percentage.
Start Left -> Current battery temperature in degrees C.
Start Right -> Battery life time.

Start + Down -> Close each of the above.
