### ISSUE TITLE
Blackscreen on adrenaline

### ISSUE THREAD

**Issue by apizzamra** [joel16/VITABattery#2]
the newest update should support adrenaline , but on adrenaline v4 the plugin cause blackscreen because when i disable the plugin the adrenaline work

**Comment by joel16** [comment]
Are you using any other plugins with this?

**Comment by apizzamra** [comment]
yes, im using oclock 
but it work for everything else

**Comment by joel16** [comment]
Do you have oclockvita set to all?
The way I have it is that oclockvita is set to certain games such as for example Persona 4 Golden, but I have VITABattery set to *ALL.

This way both of them work just fine for me, however oclock does not work on Adrenaline, but VITABattery does. I don't use oclockvita on adrenaline anyway.

**Comment by apizzamra** [comment]
yeah i set the oclock to *all*
well i guess i need to set oclock for specific game only right now....

**Comment by joel16** [comment]
Does oclockvita even work on adrenaline?  At least by itself?

**Comment by CelesteBlue-dev** [comment]
Oclock can't be used with Adrenaline.
Begin deleting oclockvita asignment to Adrenaline in config.txt.

**Comment by joel16** [comment]
Thanks for confirming @CelesteBlue-dev.
This is a problem with oclockvita, and not VITABattery.
