### ISSUE TITLE
CPU Temp

### ISSUE THREAD

**Issue by Urbs97** [joel16/VITABattery#6]
Sorry if i'm bothering you but i wanted to ask if there's a way to show the battery temp and the cpu temp via plugin?

**Comment by joel16** [comment]
You can use START + LEFT.
I'd recommend using PSV VSH Menu.

**Comment by Urbs97** [comment]
But that will only show me the battery temp right?
I was also looking for the CPU temp.

**Comment by joel16** [comment]
AFAIK there isn't any function that reports the CPU temperature.
