### ISSUE TITLE
Not working as it should on Adrenaline

### ISSUE THREAD

**Issue by AlessandroDiGioacchino** [joel16/VITABattery#7]
The battery percentage is only displayed when I open Adrenaline settings. Shouldn't it be always displayed in-game?
I'm on 3.68, Adrenaline v6.7.

**Comment by joel16** [comment]
No you don't need this in adrenaline. Adrenaline already shows you your battery percent.

**Comment by AlessandroDiGioacchino** [comment]
Excuse me?
I'm looking for a way to show the battery level in-game. How would I do that using Adrenaline?

For anyone who reads this: the plugin does not work on Adrenaline and there's no way to natively show the battery percentage on there. It's useless to install this plugin if you plan to use it as an alternative to PSV-VSH (which can't be used on Adrenaline)
